### ISSUE TITLE
Add default export

### ISSUE THREAD

**Issue by wooorm** [remcohaszing/rehype-mdx-title#1]
Most plugins in unified/remark/rehype use a default export, which allows them to be loaded when specifiers are unknown (e.g.m the engine).

Both a named and a specifier can be allowed, so this can be a minor

**Comment by remcohaszing** [comment]
I prefer named exports, but I agree default exports fit better in the remark ecosystem. I’ve already got local breaking changes to make `remark-mdx-frontmatter` ESM only and compatible with the latest mdast changes.  So I can just drop the named exports in the next major release.

**Comment by yordis** [comment]
@remcohaszing need help with this one?

**Comment by remcohaszing** [comment]
> @remcohaszing need help with this one?

I appreciate the offer, but it's more a downstream issue I’m having with this.

I would like to combine this with the conversion to ESM. The main reason this is on hold, is because I use this in a code base where it needs to be imported using Jest, TypeScript, and `ts-node`.

Since I haven’t gotten that to work yet, I haven’t changed this yet. It's functional with named exports, but if someone really wants to use this as a default export (i.e. with `unified-engine`), I’ll convert to a default import..

**Comment by wooorm** [comment]
Coincidentally, I just got bit by this again right now 😅😬

**Comment by wooorm** [comment]
You can update the package and move to ESM while keeping on using the previous version of this package there though?

**Comment by yordis** [comment]
To be honest, I am in the named-export crowd 😄 just wanna to help

**Comment by remcohaszing** [comment]
> To be honest, I am in the named-export crowd :smile:

Me too :smile:

The only reason I want to convert my plugins to default exports is for consistency within the unified ecosystem.

> just wanna to help

Cool! If you can convert this to use ESM, I’ll gladly accept a PR. Note TypeScript will need to be configured to output ESM as well.

**Comment by michaeloliverx** [comment]
I love named exports, I think both can be specified to get the best of both worlds?

**Comment by remcohaszing** [comment]
Version 2.0.0 now uses a default export.
